### ISSUE TITLE
请教论文中公式(4)的问题

### ISSUE THREAD

**Issue by cape-zck** [LutingWang/HEAD#3]
作者您好：
      感谢您在ECCV2022上关于检测蒸馏上优秀的工作，近日我在学习你们相关的工作，有几个问题不是很理解，想请教下。
     1.公式（4）是否应该为Teacher和Assistant作蒸馏呢，即红色标红的地方为右上标修改为A，因为这边的内容似乎是在介绍Assistant-based KD。如果是Assistant的话，请问这里为什么还要加linear Layer符号呢，不应该是和Teacher的检测头同构直接作L2 LOSS无需调整size么。

**Comment by LutingWang** [comment]
感谢关注。公式 (4) 存在一个笔误，应该是 $\mathcal{L}_l^A = \mathcal{D}({F}_l^T, \phi({F}_l^A))$ 。

这里的线性层主要是增加一些灵活性，因为严格要求教师和 assistant 的特征对齐可能会向 student backbone 引入噪声。 adaptation layer 可以一定程度上缓解这个问题。在许多以往工作当中也会引入这样的 adaptation layer 。

**Comment by cape-zck** [comment]
> 

好的明白，非常感谢！
